# This is an exmaple of compose file for Jenkins
version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    env_file:
      - .env
    ports:
      - ${JENKINS_UI_PORT}:8080
      - ${JENKINS_COMMUNICATION_PORT}:50000
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

networks:
  jenkins-net:
    name: jenkins-net