# This is an exmaple of compose file for Jenkins
version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.60.3
    container_name: jenkins
    privileged: true
    user: root
    env_file:
      - .env
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock